name: mlops-intro-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          apt-get update -qq
          pip install -r requirements.txt
          python model.py

          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md

          cml-send-comment report.md
